export default {
    TOGETHER_API_KEY: process.env.TOGETHER_API_KEY || "",
    TOGETHER_API: process.env.TOGETHER_API || "",
    FLIGHT_API_KEY: process.env.FLIGHT_API_KEY || "",
    FLIGHT_API: process.env.FLIGHT_API || "",
    HOTELS_API: process.env.HOTELS_API || "",
    HOTELS_API_KEY: process.env.HOTELS_API_KEY || "",
    ATTRACTIONS_API: process.env.ATTRACTIONS_API || "",
    ATTRACTIONS_API_KEY: process.env.ATTRACTIONS_API_KEY || "",
    DB_HOST: process.env.DB_HOST || "localhost",
    DB_PORT: Number(String(process.env.DB_PORT)) || 5432,
    DB_USER: process.env.DB_USER || "postgres",
    DB_PASSWORD: process.env.DB_PASSWORD || "password",
    DB_NAME: process.env.DB_NAME || "postgres",
}